### PR TITLE
Carthage compatible project 

### PR DESCRIPTION
**Pull request by dskeppstedt**
I wanted the project to be compatible with Carthage so I fixed that. Perhaps you would like this to be in the official repo as well.

Thanks for a great lib anyway!

### CODE REVIEW

**Comment by davbeck** [comment]
Does this pass `pod lib lint`? I'm actually looking into switching to Carthage myself, but we must maintain compatibility with Cocoapods as well.

**Comment by DavidSkeppstedt** [comment]
erm... good question. Since I do not use Cocoapods I do not know. I might look into that if I find the time.

**Comment by travisjeffery** [comment]
any update here?

**Comment by dskeppstedt** [comment]
@travisjeffery Not from my side.

**Comment by davbeck** [comment]
I just added support for Carthage in the develop branch.

**Pull request closed without merging**
